spring:
  profiles:
    active: dev
logging:
  level:
    root: info
    practice.practicedemo.springboot.TestRESTful.ArticleController: debug
  file:
    path: D:\logs
    name: D:\logs\practice.log
    max-size: 10MB
    max-history: 7
  pattern:
    console: '%red(%d{yyyy-MM-dd HH:mm:ss}) %green([%thread]) %highlight(%-5level) %boldMagenta(%logger{10}) - %cyan(%msg%n)'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger : %msg%n'

